POST http://devbox:28080/order/create HTTP/1.1
content-type: application/json

{
}

###

POST http://devbox:28080/order/create HTTP/1.1
content-type: application/json

{
    "serviceId": "SVC0000000",
    "orderId": 100
}

###

POST http://devbox:28080/order/route/SVC0000000 HTTP/1.1
content-type: application/json

["100:5",
 "105"
]


###

POST http://devbox:2s8080/order/unroute/SVC0000000 HTTP/1.1
content-type: application/json

[]

###

GET http://devbox:28080/order/id/101