spring:
  application:
    name: order-service
  config:
    import: "optional:consul:"
  cloud:
    consul:
      enabled: true
      host: ${HOST_IP:localhost}
      discovery:
        instance-id: ${HOSTNAME}
        ip-address: ${POD_IP:localhost}
        prefer-ip-address: true
      config:
        format: yaml