POST http://devbox:18080/ne/create HTTP/1.1
content-type: application/json

{
    "model": "7750 SR-12 MSE"
}

###

POST http://devbox:18080/ne/assign/route/100/5 HTTP/1.1
content-type: application/json

{
    "orderId": 100,
    "serviceId": "SVC0000000"
}

###

POST http://devbox:18080/ne/assign/route/100 HTTP/1.1
content-type: application/json

{
    "orderId": 100,
    "serviceId": "SVC0000000"
}

###

POST http://devbox:18080/ne/unassign/route HTTP/1.1
content-type: application/json

{
  "neId": 100,
  "model": "7750 SR-12 MSE",
  "ports": {
    "1/1/1": {
      "port": "1/1/1",
      "tags": {
        "1": {
          "tag": 1,
          "ord": {
            "orderId": 100,
            "serviceId": "SVC0000000"
          }
        },
        "2": {
          "tag": 2,
          "ord": {
            "orderId": 100,
            "serviceId": "SVC0000000"
          }
        }
      }
    }
  }
}